import type { CaseDefinition, DecisionLogEntry } from './types';
import { compareToBestPath } from './best-path';
import { gradeForRatio, totalScoreFromLog } from './scoring';
import { tr, type Locale } from './i18n';

export interface LessonPlanInput {
  caseDef: CaseDefinition;
  log: DecisionLogEntry[];
  elapsedGameMin: number;
  totalCostSGD: number;
  burden?: { timeOffWorkHours: number; financialWorry: number; sleepDebt: number };
  profile?: { name: string; wardClass: string; chasTier: string; hasIntegratedShield: boolean };
  /** Locale to resolve LocalisedString fields with. Defaults to English. */
  locale?: Locale;
  /** Per-decision learner reflection notes, keyed by decisionId. Surfaced
   *  as a blockquote after each decision in the exported lesson plan. */
  notes?: Record<string, string>;
  /** Ordered node ids the patient visited. When supplied, a "Patient journey"
   *  section lists each stop with its facility + department + staff-perspective
   *  framing so the export reads as a clinical narrative, not just a decision
   *  list. */
  journey?: string[];
}

/**
 * Locale-specific chrome strings for the lesson-plan export (headings,
 * field labels, duration suffixes, footer). LocalisedString-shaped case
 * content is resolved separately via tr(). Falls back to English when a
 * key is missing for the requested locale.
 */
interface LessonPlanStrings {
  histDisclaimer: string;
  summary: string;
  score: string;
  inGameTime: string;
  cashOop: string;
  decisionsMade: string;
  patient: string;
  ward: string;
  chasNone: string;
  ipRider: string;
  caregiverBurden: string;
  hOffWork: string;
  worry: string;
  sleepDebt: string;
  patientJourney: string;
  decisions: string;
  chosen: string;
  bestPractice: string;
  matched: string;
  differs: string;
  rationaleChosen: string;
  rationaleBest: string;
  reference: string;
  pts: string;
  references: string;
  histCitations: string;
  footer: string;
  d: string;
  h: string;
  m: string;
}

const STRINGS: Record<Locale, LessonPlanStrings> = {
  en: {
    histDisclaimer: 'Historical scenario — educational reconstruction.',
    summary: 'Summary',
    score: 'Score',
    inGameTime: 'In-game time',
    cashOop: 'Cash out-of-pocket',
    decisionsMade: 'Decisions made',
    patient: 'Patient',
    ward: 'ward',
    chasNone: 'none',
    ipRider: 'IP rider',
    caregiverBurden: 'Caregiver burden',
    hOffWork: 'h off work',
    worry: 'worry',
    sleepDebt: 'sleep debt',
    patientJourney: 'Patient journey',
    decisions: 'Decisions',
    chosen: 'Chosen',
    bestPractice: 'Best-practice',
    matched: 'Matched best-practice.',
    differs: 'Differs from best-practice.',
    rationaleChosen: 'Rationale for chosen',
    rationaleBest: 'Rationale for best-practice',
    reference: 'Reference',
    pts: 'pts',
    references: 'References used in this case',
    histCitations: 'Historical scenario citations',
    footer: 'Generated by SG Pathway — an educational simulation. Numbers are illustrative.',
    d: 'd',
    h: 'h',
    m: 'm',
  },
  zh: {
    histDisclaimer: '历史教学情景 — 教学性重构。',
    summary: '总览',
    score: '得分',
    inGameTime: '游戏内时长',
    cashOop: '现金自付',
    decisionsMade: '已做决策',
    patient: '患者',
    ward: '病房',
    chasNone: '无',
    ipRider: 'IP附加险',
    caregiverBurden: '家属负担',
    hOffWork: '小时假',
    worry: '忧虑',
    sleepDebt: '睡眠负债',
    patientJourney: '患者就诊路径',
    decisions: '决策',
    chosen: '所选',
    bestPractice: '最佳实践',
    matched: '与最佳实践一致。',
    differs: '与最佳实践不同。',
    rationaleChosen: '所选选项依据',
    rationaleBest: '最佳实践依据',
    reference: '参考',
    pts: '分',
    references: '本案引用的指南',
    histCitations: '历史情景文献引用',
    footer: '由 SG Pathway 教学模拟生成;数值仅作示意。',
    d: '天',
    h: '小时',
    m: '分钟',
  },
  ms: {
    histDisclaimer: 'Senario sejarah — penyusunan semula untuk pendidikan.',
    summary: 'Ringkasan',
    score: 'Markah',
    inGameTime: 'Masa permainan',
    cashOop: 'Tunai dari poket',
    decisionsMade: 'Keputusan dibuat',
    patient: 'Pesakit',
    ward: 'wad',
    chasNone: 'tiada',
    ipRider: 'Pelan IP',
    caregiverBurden: 'Beban penjaga',
    hOffWork: 'j cuti kerja',
    worry: 'kebimbangan',
    sleepDebt: 'kurang tidur',
    patientJourney: 'Perjalanan pesakit',
    decisions: 'Keputusan',
    chosen: 'Dipilih',
    bestPractice: 'Amalan terbaik',
    matched: 'Sepadan dengan amalan terbaik.',
    differs: 'Berbeza daripada amalan terbaik.',
    rationaleChosen: 'Sebab pilihan',
    rationaleBest: 'Sebab amalan terbaik',
    reference: 'Rujukan',
    pts: 'mata',
    references: 'Rujukan digunakan dalam kes ini',
    histCitations: 'Petikan senario sejarah',
    footer: 'Dihasilkan oleh SG Pathway — simulasi pendidikan. Nombor adalah ilustrasi sahaja.',
    d: 'h',
    h: 'j',
    m: 'm',
  },
  ta: {
    histDisclaimer: 'வரலாற்று காட்சி — கல்வி நோக்கில் மீளமைப்பு.',
    summary: 'சுருக்கம்',
    score: 'மதிப்பெண்',
    inGameTime: 'விளையாட்டு நேரம்',
    cashOop: 'நேரடி கட்டணம்',
    decisionsMade: 'எடுக்கப்பட்ட முடிவுகள்',
    patient: 'நோயாளி',
    ward: 'பிரிவு',
    chasNone: 'இல்லை',
    ipRider: 'IP திட்டம்',
    caregiverBurden: 'பராமரிப்பாளர் சுமை',
    hOffWork: 'மணி விடுமுறை',
    worry: 'கவலை',
    sleepDebt: 'தூக்கப் பற்றாக்குறை',
    patientJourney: 'நோயாளியின் பயணம்',
    decisions: 'முடிவுகள்',
    chosen: 'தேர்ந்தெடுத்தது',
    bestPractice: 'சிறந்த நடைமுறை',
    matched: 'சிறந்த நடைமுறையுடன் பொருந்துகிறது.',
    differs: 'சிறந்த நடைமுறையிலிருந்து வேறுபடுகிறது.',
    rationaleChosen: 'தேர்வுக்கான காரணம்',
    rationaleBest: 'சிறந்த நடைமுறைக்கான காரணம்',
    reference: 'குறிப்பு',
    pts: 'புள்.',
    references: 'இந்த வழக்கில் பயன்படுத்தப்பட்ட குறிப்புகள்',
    histCitations: 'வரலாற்று காட்சி மேற்கோள்கள்',
    footer: 'SG Pathway கல்வி உருவகத்தால் உருவாக்கப்பட்டது — எண்கள் விளக்கம் மட்டுமே.',
    d: 'நா',
    h: 'ம',
    m: 'நி',
  },
};

/**
 * Generate a markdown lesson-plan summary of a completed run. Educators paste
 * it into their teaching notes, a Google Doc, Notion, etc. — every decision
 * is shown with the chosen option, the best-practice option, both rationales,
 * and the reference guideline.
 */
export function generateLessonPlan(input: LessonPlanInput): string {
  const { caseDef, log, elapsedGameMin, totalCostSGD, burden, profile } = input;
  const loc = input.locale ?? 'en';
  const S = STRINGS[loc] ?? STRINGS.en;
  const L = (v: unknown) => tr(v as Parameters<typeof tr>[0], loc);
  const { earned, max } = totalScoreFromLog(log);
  const ratio = max > 0 ? earned / max : 0;
  const grade = gradeForRatio(ratio);
  const diff = compareToBestPath(caseDef, log);

  const lines: string[] = [];
  lines.push(`# ${L(caseDef.title)}`);
  lines.push('');
  if (caseDef.historical) lines.push(`> ${S.histDisclaimer}`);
  lines.push(L(caseDef.blurb));
  lines.push('');
  lines.push(`## ${S.summary}`);
  lines.push(`- **${S.score}**: ${earned.toFixed(1)} / ${max.toFixed(1)} — **${grade.grade}** (${(ratio * 100).toFixed(0)}%)`);
  lines.push(`- **${S.inGameTime}**: ${fmtDuration(elapsedGameMin, S)}`);
  lines.push(`- **${S.cashOop}**: S$${totalCostSGD.toFixed(0)}`);
  lines.push(`- **${S.decisionsMade}**: ${log.length}`);
  if (profile) {
    lines.push(
      `- **${S.patient}**: ${profile.name} · ${S.ward} ${profile.wardClass} · CHAS ${
        profile.chasTier === 'none' ? S.chasNone : profile.chasTier
      }${profile.hasIntegratedShield ? ` · ${S.ipRider}` : ''}`,
    );
  }
  if (burden) {
    lines.push(
      `- **${S.caregiverBurden}**: ${burden.timeOffWorkHours.toFixed(0)}${S.hOffWork} · ${S.worry} ${burden.financialWorry.toFixed(0)}/100 · ${S.sleepDebt} ${burden.sleepDebt.toFixed(0)}/100`,
    );
  }
  lines.push('');

  if (input.journey && input.journey.length > 0) {
    const stops = input.journey
      .map((id) => caseDef.pathway.find((n) => n.id === id))
      .filter((n): n is NonNullable<typeof n> => n != null);
    const rendered: string[] = [];
    for (const n of stops) {
      const framing = L(n.framing.staff);
      if (!framing) continue;
      rendered.push(`- **${n.facility ?? caseDef.primaryFacility}** · ${n.department} — ${framing}`);
    }
    if (rendered.length > 0) {
      lines.push(`## ${S.patientJourney}`);
      lines.push(...rendered);
      lines.push('');
    }
  }

  if (diff.length > 0) {
    lines.push(`## ${S.decisions}`);
    diff.forEach((row, i) => {
      lines.push(`### ${i + 1}. ${L(row.prompt)}`);
      if (row.yours) {
        lines.push(`- **${S.chosen}**: ${L(row.yours.label)} — ${row.yours.score.toFixed(1)} / ${row.yours.maxScore.toFixed(1)} ${S.pts}`);
      }
      lines.push(`- **${S.bestPractice}**: ${L(row.best.label)} — ${row.best.score.toFixed(1)} ${S.pts}`);
      lines.push(row.match ? `- *${S.matched}*` : `- *${S.differs}*`);
      const node = caseDef.pathway.find((n) => n.decision?.id === row.decisionId);
      // Match by resolved label so we find the option regardless of locale.
      const chosen = node?.decision?.options.find((o) => L(o.label) === L(row.yours?.label));
      const best = node?.decision?.options.find((o) => L(o.label) === L(row.best.label));
      if (chosen?.rationale) lines.push(`- ${S.rationaleChosen}: ${L(chosen.rationale)}`);
      if (best?.rationale && best !== chosen) lines.push(`- ${S.rationaleBest}: ${L(best.rationale)}`);
      if (node?.decision?.reference?.label) lines.push(`- ${S.reference}: *${L(node.decision.reference.label)}*`);
      const note = input.notes?.[row.decisionId]?.trim();
      if (note) {
        lines.push('');
        for (const ln of note.split(/\r?\n/)) lines.push(`> ${ln}`);
      }
      lines.push('');
    });
  }

  if (caseDef.guidelines.length > 0) {
    lines.push(`## ${S.references}`);
    for (const g of caseDef.guidelines) {
      lines.push(`- **${L(g.label)}** — ${L(g.body)}`);
    }
    lines.push('');
  }

  if (caseDef.historical && caseDef.citations && caseDef.citations.length > 0) {
    lines.push(`## ${S.histCitations}`);
    caseDef.citations.forEach((c, i) => lines.push(`${i + 1}. ${c}`));
    lines.push('');
  }

  lines.push('---');
  lines.push(S.footer);

  return lines.join('\n');
}

function fmtDuration(min: number, S: LessonPlanStrings): string {
  const h = Math.floor(min / 60);
  const d = Math.floor(h / 24);
  const rh = h % 24;
  const rm = min % 60;
  if (d > 0) return `${d}${S.d} ${rh}${S.h}`;
  if (h > 0) return `${h}${S.h} ${rm}${S.m}`;
  return `${min}${S.m}`;
}
