import type { CaseDefinition, DecisionLogEntry } from './types';
import { compareToBestPath } from './best-path';
import { gradeForRatio, totalScoreFromLog } from './scoring';
import { tr, type Locale } from './i18n';

export interface LessonPlanInput {
  caseDef: CaseDefinition;
  log: DecisionLogEntry[];
  elapsedGameMin: number;
  totalCostSGD: number;
  burden?: { timeOffWorkHours: number; financialWorry: number; sleepDebt: number };
  profile?: { name: string; wardClass: string; chasTier: string; hasIntegratedShield: boolean };
  /** Locale to resolve LocalisedString fields with. Defaults to English. */
  locale?: Locale;
  /** Per-decision learner reflection notes, keyed by decisionId. Surfaced
   *  as a blockquote after each decision in the exported lesson plan. */
  notes?: Record<string, string>;
}

/**
 * Generate a markdown lesson-plan summary of a completed run. Educators paste
 * it into their teaching notes, a Google Doc, Notion, etc. — every decision
 * is shown with the chosen option, the best-practice option, both rationales,
 * and the reference guideline.
 */
export function generateLessonPlan(input: LessonPlanInput): string {
  const { caseDef, log, elapsedGameMin, totalCostSGD, burden, profile } = input;
  const loc = input.locale ?? 'en';
  const L = (v: unknown) => tr(v as Parameters<typeof tr>[0], loc);
  const { earned, max } = totalScoreFromLog(log);
  const ratio = max > 0 ? earned / max : 0;
  const grade = gradeForRatio(ratio);
  const diff = compareToBestPath(caseDef, log);

  const lines: string[] = [];
  lines.push(`# ${L(caseDef.title)}`);
  lines.push('');
  if (caseDef.historical) lines.push('> Historical scenario — educational reconstruction.');
  lines.push(L(caseDef.blurb));
  lines.push('');
  lines.push('## Summary');
  lines.push(`- **Score**: ${earned.toFixed(1)} / ${max.toFixed(1)} — **${grade.grade}** (${(ratio * 100).toFixed(0)}%)`);
  lines.push(`- **In-game time**: ${fmtDuration(elapsedGameMin)}`);
  lines.push(`- **Cash out-of-pocket**: S$${totalCostSGD.toFixed(0)}`);
  lines.push(`- **Decisions made**: ${log.length}`);
  if (profile) {
    lines.push(
      `- **Patient**: ${profile.name} · ward ${profile.wardClass} · CHAS ${
        profile.chasTier === 'none' ? 'none' : profile.chasTier
      }${profile.hasIntegratedShield ? ' · IP rider' : ''}`,
    );
  }
  if (burden) {
    lines.push(
      `- **Caregiver burden**: ${burden.timeOffWorkHours.toFixed(0)}h off work · worry ${burden.financialWorry.toFixed(0)}/100 · sleep debt ${burden.sleepDebt.toFixed(0)}/100`,
    );
  }
  lines.push('');

  if (diff.length > 0) {
    lines.push('## Decisions');
    diff.forEach((row, i) => {
      lines.push(`### ${i + 1}. ${L(row.prompt)}`);
      if (row.yours) {
        lines.push(`- **Chosen**: ${L(row.yours.label)} — ${row.yours.score.toFixed(1)} / ${row.yours.maxScore.toFixed(1)} pts`);
      }
      lines.push(`- **Best-practice**: ${L(row.best.label)} — ${row.best.score.toFixed(1)} pts`);
      lines.push(row.match ? '- *Matched best-practice.*' : '- *Differs from best-practice.*');
      const node = caseDef.pathway.find((n) => n.decision?.id === row.decisionId);
      // Match by resolved label so we find the option regardless of locale.
      const chosen = node?.decision?.options.find((o) => L(o.label) === L(row.yours?.label));
      const best = node?.decision?.options.find((o) => L(o.label) === L(row.best.label));
      if (chosen?.rationale) lines.push(`- Rationale for chosen: ${L(chosen.rationale)}`);
      if (best?.rationale && best !== chosen) lines.push(`- Rationale for best-practice: ${L(best.rationale)}`);
      if (node?.decision?.reference?.label) lines.push(`- Reference: *${L(node.decision.reference.label)}*`);
      const note = input.notes?.[row.decisionId]?.trim();
      if (note) {
        lines.push('');
        for (const ln of note.split(/\r?\n/)) lines.push(`> ${ln}`);
      }
      lines.push('');
    });
  }

  if (caseDef.guidelines.length > 0) {
    lines.push('## References used in this case');
    for (const g of caseDef.guidelines) {
      lines.push(`- **${L(g.label)}** — ${L(g.body)}`);
    }
    lines.push('');
  }

  if (caseDef.historical && caseDef.citations && caseDef.citations.length > 0) {
    lines.push('## Historical scenario citations');
    caseDef.citations.forEach((c, i) => lines.push(`${i + 1}. ${c}`));
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by SG Pathway — an educational simulation. Numbers are illustrative.');

  return lines.join('\n');
}

function fmtDuration(min: number): string {
  const h = Math.floor(min / 60);
  const d = Math.floor(h / 24);
  const rh = h % 24;
  const rm = min % 60;
  if (d > 0) return `${d}d ${rh}h`;
  if (h > 0) return `${h}h ${rm}m`;
  return `${min}m`;
}
